name: Run Telegram Bot Every 3 Hours

on:
  schedule:
    - cron: "0 */3 * * *" 
  workflow_dispatch: 

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install python-telegram-bot --upgrade

      - name: Run the Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Secure bot token
        run: python auto_forward_bot.py